# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nc2cli < Formula
  desc "CLI tool to manage Nutanix Cloud Clusters (NC2)"
  homepage "https://github.com/squasta/NC2CLI-Go"
  version "0.2.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/squasta/NC2CLI-Go/releases/download/v0.2.6/NC2CLI-Go_0.2.6_darwin_amd64.tar.gz"
      sha256 "303ed5de8ea1f990e3f064a259757655df9142993a4b58f069ed03b78823324c"

      define_method(:install) do
        bin.install "nc2cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/squasta/NC2CLI-Go/releases/download/v0.2.6/NC2CLI-Go_0.2.6_darwin_arm64.tar.gz"
      sha256 "19cf093f45be461448bd850be2575d5cb4fb837e16ed48044c8a692e3990d84d"

      define_method(:install) do
        bin.install "nc2cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/squasta/NC2CLI-Go/releases/download/v0.2.6/NC2CLI-Go_0.2.6_linux_amd64.tar.gz"
      sha256 "7f6fa6eef2a78cf3306c3659c9c3307d71b329ebfe2ee71f86bf760b000174f8"
      define_method(:install) do
        bin.install "nc2cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/squasta/NC2CLI-Go/releases/download/v0.2.6/NC2CLI-Go_0.2.6_linux_arm64.tar.gz"
      sha256 "855d57ea1a6fd9b3379b9feb6a11e0b347b89fb1f26d1a41aed51d447cd64dfe"
      define_method(:install) do
        bin.install "nc2cli"
      end
    end
  end

  test do
    system "#{bin}/nc2cli --help"
  end
end
