# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nc2cli < Formula
  desc "CLI tool to manage Nutanix Cloud Clusters (NC2)"
  homepage "https://github.com/squasta/NC2CLI-Go"
  version "0.2.8"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/squasta/NC2CLI-Go/releases/download/v0.2.8/nc2cli_0.2.8_darwin_amd64.tar.gz"
      sha256 "ec26ef854e760778ee122849e28e4a56fbecec7dbfe71976103f9871267b8c25"

      define_method(:install) do
        bin.install "nc2cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/squasta/NC2CLI-Go/releases/download/v0.2.8/nc2cli_0.2.8_darwin_arm64.tar.gz"
      sha256 "25ab79d1a673da517002f9130f89fe955f8c816d98ef951c2a107e80a755d24c"

      define_method(:install) do
        bin.install "nc2cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/squasta/NC2CLI-Go/releases/download/v0.2.8/nc2cli_0.2.8_linux_amd64.tar.gz"
      sha256 "9c6ea511cdbbdd03b1aae05319f9afa869b21ff66055ce8c8556585885cdeb62"
      define_method(:install) do
        bin.install "nc2cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/squasta/NC2CLI-Go/releases/download/v0.2.8/nc2cli_0.2.8_linux_arm64.tar.gz"
      sha256 "3ebb58a7769786b167eb2106f805f527161f79589dfa5568fe54af029c67510f"
      define_method(:install) do
        bin.install "nc2cli"
      end
    end
  end

  test do
    system "#{bin}/nc2cli --help"
  end
end
