# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nc2cli < Formula
  desc "CLI tool to manage Nutanix Cloud Clusters (NC2)"
  homepage "https://github.com/squasta/NC2CLI-Go"
  version "0.2.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/squasta/NC2CLI-Go/releases/download/v0.2.7/NC2CLI-Go_0.2.7_darwin_amd64.tar.gz"
      sha256 "595b3f0bd49ee67f32b31cf6424c3bf8af6d17a3d8a71e07f55d8b526ec9d3a8"

      define_method(:install) do
        bin.install "nc2cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/squasta/NC2CLI-Go/releases/download/v0.2.7/NC2CLI-Go_0.2.7_darwin_arm64.tar.gz"
      sha256 "f3ffc2b408c05e5e60b0a50089609d8727325a3bdafb9f37fb643c2576342cb9"

      define_method(:install) do
        bin.install "nc2cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/squasta/NC2CLI-Go/releases/download/v0.2.7/NC2CLI-Go_0.2.7_linux_amd64.tar.gz"
      sha256 "195d4143cad93ea5a718a3cb86db4fcf4eaed09d8bf8861e3a79e87907a59de2"
      define_method(:install) do
        bin.install "nc2cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/squasta/NC2CLI-Go/releases/download/v0.2.7/NC2CLI-Go_0.2.7_linux_arm64.tar.gz"
      sha256 "730e0a912a04c22f9f0b1025bd4c3f0aefacf782236e08f4c4b7d55aaec69c8f"
      define_method(:install) do
        bin.install "nc2cli"
      end
    end
  end

  test do
    system "#{bin}/nc2cli --help"
  end
end
