# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pcwin < Formula
  desc "CLI to list Windows VMs hosted on a Nutanix Prism Central cluster."
  homepage "https://github.com/squasta/pcwin"
  version "0.3.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/squasta/pcwin/releases/download/v0.3.2/pcwin_0.3.2_darwin_x86_64.tar.gz"
      sha256 "2e1b2c4e428e9cec19ef63081b8b8d1739e1ad5fb82da2a4ee50c740e3157ce9"

      define_method(:install) do
        bin.install "pcwin"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/squasta/pcwin/releases/download/v0.3.2/pcwin_0.3.2_darwin_arm64.tar.gz"
      sha256 "ed9d92701ba58c19c9e085ba7ab26ba61229d2be4227206a301b8ea7f15222f6"

      define_method(:install) do
        bin.install "pcwin"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/squasta/pcwin/releases/download/v0.3.2/pcwin_0.3.2_linux_x86_64.tar.gz"
      sha256 "716d9531ecc6cf1e18e55add621c20530f5e167d88e3064ac3f3166f77fe071a"
      define_method(:install) do
        bin.install "pcwin"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/squasta/pcwin/releases/download/v0.3.2/pcwin_0.3.2_linux_arm64.tar.gz"
      sha256 "1ad9078cad69e03bd31b17ad10e86636eeb802bea738760457583a26eb029495"
      define_method(:install) do
        bin.install "pcwin"
      end
    end
  end

  test do
    system "#{bin}/pcwin", "--version"
  end
end
