# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pcwin < Formula
  desc "CLI to list Windows VMs hosted on a Nutanix Prism Central cluster."
  homepage "https://github.com/squasta/pcwin"
  version "0.3.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/squasta/pcwin/releases/download/v0.3.1/pcwin_0.3.1_darwin_x86_64.tar.gz"
      sha256 "008e3eee0f9b860266cd3d88163aac32cf28cd2002e97b2d15f9531554ad64f4"

      define_method(:install) do
        bin.install "pcwin"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/squasta/pcwin/releases/download/v0.3.1/pcwin_0.3.1_darwin_arm64.tar.gz"
      sha256 "f491691956bb0b35b725c99b0104d9d8e2b8dbeab4ca83b9b7e9783cf6a2cbf6"

      define_method(:install) do
        bin.install "pcwin"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/squasta/pcwin/releases/download/v0.3.1/pcwin_0.3.1_linux_x86_64.tar.gz"
      sha256 "9ff4b2acbe56450982f6d38539a4ab1b48bbfeb3016cd18cfe808cb1b2c49b80"
      define_method(:install) do
        bin.install "pcwin"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/squasta/pcwin/releases/download/v0.3.1/pcwin_0.3.1_linux_arm64.tar.gz"
      sha256 "68a1ae2ea1e8f7964b8e508f25eefae562480212abb9ce412b6a60ed9e72f68b"
      define_method(:install) do
        bin.install "pcwin"
      end
    end
  end

  test do
    system "#{bin}/pcwin", "--version"
  end
end
